plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false
